# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UVL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UVL
pod 'GONMarkupParser'
pod "QBImagePickerController"

  target 'UVLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UVLUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
